# Generated by Django 3.0.7 on 2020-08-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('country', models.CharField(max_length=30)),
                ('year_of_foundation', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
    ]
